Fix PyGIWarnings and NameError
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 163, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/reflection.activity/ReflectionActivity.py", line 13, in <module>
    gi.require_version('Gtk', '3.0')
NameError: name 'gi' is not defined

Due to NameError, activity fails to start